# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RFMGeneratorGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from detectinterpreter import find_arcgis_pro_python
from rfm_generator import run_sequential



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1052, 774)
        MainWindow.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 10, 1041, 731))
        self.frame.setMouseTracking(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(0, 90, 601, 341))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.layoutWidget = QtWidgets.QWidget(self.frame_6)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 601, 301))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget_4 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 40, 491, 51))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.filepathexcel = QtWidgets.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filepathexcel.setFont(font)
        self.filepathexcel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.filepathexcel.setObjectName("filepathexcel")
        self.horizontalLayout_6.addWidget(self.filepathexcel)
        self.BrowseExcelFile = QtWidgets.QPushButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.BrowseExcelFile.setFont(font)
        self.BrowseExcelFile.setObjectName("BrowseExcelFile")
        self.horizontalLayout_6.addWidget(self.BrowseExcelFile)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(0, 20, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("c")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 40, 491, 51))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.filepathobj = QtWidgets.QLineEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filepathobj.setFont(font)
        self.filepathobj.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.filepathobj.setObjectName("filepathobj")
        self.horizontalLayout_5.addWidget(self.filepathobj)
        self.BrowseObjFile = QtWidgets.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.BrowseObjFile.setFont(font)
        self.BrowseObjFile.setObjectName("BrowseObjFile")
        self.horizontalLayout_5.addWidget(self.BrowseObjFile)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(0, 20, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget_5 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget_5.setGeometry(QtCore.QRect(0, 40, 491, 51))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.filepathcontour = QtWidgets.QLineEdit(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filepathcontour.setFont(font)
        self.filepathcontour.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.filepathcontour.setObjectName("filepathcontour")
        self.horizontalLayout_7.addWidget(self.filepathcontour)
        self.BrowseContour = QtWidgets.QPushButton(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.BrowseContour.setFont(font)
        self.BrowseContour.setObjectName("BrowseContour")
        self.horizontalLayout_7.addWidget(self.BrowseContour)
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(0, 20, 291, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.frame_4)
        self.logo = QtWidgets.QLabel(self.frame)
        self.logo.setGeometry(QtCore.QRect(680, 90, 261, 311))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/newPrefix/alberta-share.png"))
        self.logo.setObjectName("logo")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(210, 540, 581, 191))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget1.setGeometry(QtCore.QRect(130, 110, 321, 71))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.run = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.run.setFont(font)
        self.run.setStyleSheet("            QPushButton {\n"
"                background-color: white;\n"
"                color: black;\n"
"                border-style: white;\n"
"                border-radius: 10px;  /* round corners */\n"
"                padding: 6px;\n"
"                min-height: 30px;\n"
"                border-width: 5px;\n"
"                border-color: #00ADEF;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #0077CC;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #005F99;\n"
"            }")
        self.run.setObjectName("run")
        self.horizontalLayout.addWidget(self.run)
        self.stop = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI Light")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.stop.setFont(font)
        self.stop.setStyleSheet("            QPushButton {\n"
"                background-color: white;\n"
"                color: black;\n"
"                border-style: white;\n"
"                border-radius: 10px;  /* round corners */\n"
"                padding: 6px;\n"
"                min-height: 30px;\n"
"                border-width: 5px;\n"
"                border-color: #00ADEF;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: red;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #d46d68;\n"
"            }")
        self.stop.setObjectName("stop")
        self.horizontalLayout.addWidget(self.stop)
        self.progressBar = QtWidgets.QProgressBar(self.frame_5)
        self.progressBar.setGeometry(QtCore.QRect(10, 70, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.progresstext = QtWidgets.QLineEdit(self.frame_5)
        self.progresstext.setGeometry(QtCore.QRect(172, 40, 231, 22))
        self.progresstext.setObjectName("progresstext")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(10, 430, 671, 91))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.layoutWidget_6 = QtWidgets.QWidget(self.frame_7)
        self.layoutWidget_6.setGeometry(QtCore.QRect(0, 40, 491, 51))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.filepathinterpreter = QtWidgets.QLineEdit(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.filepathinterpreter.setFont(font)
        self.filepathinterpreter.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.filepathinterpreter.setObjectName("filepathinterpreter")
        self.horizontalLayout_8.addWidget(self.filepathinterpreter)
        self.browserinterp = QtWidgets.QPushButton(self.frame_7)
        self.browserinterp.setGeometry(QtCore.QRect(580, 50, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.browserinterp.setFont(font)
        self.browserinterp.setObjectName("browserinterp")
        self.autodetectinterp = QtWidgets.QPushButton(self.frame_7)
        self.autodetectinterp.setGeometry(QtCore.QRect(494, 50, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.autodetectinterp.setFont(font)
        self.autodetectinterp.setObjectName("autodetectinterp")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setGeometry(QtCore.QRect(0, 10, 321, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 20, 971, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(29)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(760, 440, 271, 80))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setObjectName("label_7")
        self.selectfieldcontour = QtWidgets.QComboBox(self.frame_8)
        self.selectfieldcontour.setGeometry(QtCore.QRect(20, 40, 191, 22))
        self.selectfieldcontour.setObjectName("selectfieldcontour")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1052, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.BrowseExcelFile.clicked.connect(lambda: self.openFileNameDialog(self.filepathexcel))
        self.BrowseObjFile.clicked.connect(lambda: self.openFileNameDialog(self.filepathobj))
        self.BrowseContour.clicked.connect(lambda: self.openFileNameDialog(self.filepathcontour))
        self.browserinterp.clicked.connect(lambda: self.openFileNameDialog(self.filepathinterpreter))

        self.autodetectinterp.clicked.connect(self.autoDetectInterpreter)
        self.run.clicked.connect(self.validateAndRun)
        




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.filepathexcel.setPlaceholderText(_translate("MainWindow", "Select a file..."))
        self.BrowseExcelFile.setText(_translate("MainWindow", "Browse..."))
        self.label_3.setText(_translate("MainWindow", "Select Excel Input / Output File *"))
        self.filepathobj.setPlaceholderText(_translate("MainWindow", "Select a file..."))
        self.BrowseObjFile.setText(_translate("MainWindow", "Browse..."))
        self.label_4.setText(_translate("MainWindow", "Select Object (.obj) File *"))
        self.filepathcontour.setPlaceholderText(_translate("MainWindow", "Select a file..."))
        self.BrowseContour.setText(_translate("MainWindow", "Browse..."))
        self.label_5.setText(_translate("MainWindow", "Select Location to Save Contour *"))
        self.run.setText(_translate("MainWindow", "Run"))
        self.stop.setText(_translate("MainWindow", "Stop Execution"))
        self.filepathinterpreter.setPlaceholderText(_translate("MainWindow", "Select a file..."))
        self.browserinterp.setText(_translate("MainWindow", "Browse..."))
        self.autodetectinterp.setText(_translate("MainWindow", "Auto-Detect"))
        self.label_6.setText(_translate("MainWindow", "Select ArcGIS Pro Python Interpreter *"))
        self.label_2.setText(_translate("MainWindow", "MACS Project: Reduced Form Model Creation Tool"))
        self.label_7.setText(_translate("MainWindow", "Select the Field to Contour *"))


    def openFileNameDialog(self, line_edit):
        options = QFileDialog.Options()
        file_name, _ = QFileDialog.getOpenFileName(None, "Select File", "", "All Files (*);;Text Files (*.txt)", options=options)
        if file_name:
                line_edit.setText(file_name)

    def autoDetectInterpreter(self):
        """
        Automatically detects the ArcGIS Pro Python interpreter and updates the QLineEdit.
        If not found, shows a message box.
        """
        interpreter_path = find_arcgis_pro_python()
        if interpreter_path:
                self.filepathinterpreter.setText(interpreter_path)
        else:
                QMessageBox.warning(None, "Interpreter Not Found", "ArcGIS Pro Python interpreter not found.")

    def validateFields(self):
        # List of QLineEdit widgets with required inputs
        required_fields = {
                self.filepathexcel: "Excel Input / Output File",
                self.filepathobj: "Object (.obj) File",
                self.filepathcontour: "Location to Save Contour",
                self.filepathinterpreter: "ArcGIS Pro Python Interpreter"
        }
        
        missing_fields = [name for field, name in required_fields.items() if not field.text().strip()]
        
        if missing_fields:
                QMessageBox.warning(None, "Missing Information", "Please fill in all required fields: " + ", ".join(missing_fields) + ".")
                return False
        return True
    
    def validateAndRun(self):
        """
        Validates the required fields and runs the main process if validation is successful.
        """
        if self.validateFields():
                self.runMainProcess()
        else:
                # If validation fails, an appropriate message box will be shown from validateFields.
                pass


    def runMainProcess(self):
        try:
                excel_path = self.filepathexcel.text()  # Assuming 'filepathexcel' is the QLineEdit for Excel path
                obj_path = self.filepathobj.text()  # Assuming 'filepathobj' is the QLineEdit for .obj file path

                run_sequential(excel_path, obj_path)
                QMessageBox.information(None, "Process Completed", "RFM processing completed successfully.")
        except Exception as e:
                QMessageBox.critical(None, "Process Error", str(e))




import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
